version: '3'

services: 

    ifood-backend-challenge:

        image: ifood-backend-challenge
        
        expose:
            - 8080
        
        ports: 
            - 8080:8080
        
        build: 
            context: ./
            dockerfile: Dockerfile
        
        env_file:
            - .env

        dns:
            - 8.8.8.8
            - 4.4.4.4
            - 192.168.9.45